package com.internship.pbt.findimage.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.internship.pbt.findimage.db.Images;

import com.internship.pbt.findimage.db.ImagesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig imagesDaoConfig;

    private final ImagesDao imagesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        imagesDaoConfig = daoConfigMap.get(ImagesDao.class).clone();
        imagesDaoConfig.initIdentityScope(type);

        imagesDao = new ImagesDao(imagesDaoConfig, this);

        registerDao(Images.class, imagesDao);
    }
    
    public void clear() {
        imagesDaoConfig.getIdentityScope().clear();
    }

    public ImagesDao getImagesDao() {
        return imagesDao;
    }

}
